version: "3.8"

services:
  tika:
    image: apache/tika:latest
    container_name: tika
    ports:
      - "9998:9998"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    
      - "15672:15672"  
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: pdf_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - TIKA_URL=http://tika:9998
    depends_on:
      - tika
      - rabbitmq
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    environment:
      - RABBITMQ_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - TIKA_URL=http://tika:9998
    depends_on:
      - rabbitmq
      - redis
      - tika
    restart: unless-stopped